Wtiau.Health.Web/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Wtiau.Health.Web.Models.Domian;
using Wtiau.Health.Web.Models.ViewModels;
using Wtiau.Health.Web.Models.Repository;
using System.Data.Entity;
using System.Net;

namespace Wtiau.Health.Web.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class QuestionController : Controller
    {
        HealthEntities db = new HealthEntities();

        public ActionResult Index(int id, string formDisplay)
        {
            var _Qusetion = db.Tbl_Question.Where(x => x.Question_IsDelete == false && x.Tbl_FormStep.FS_FormID == id).Select(x => new Model_QusetionList
            {
                ID = x.Question_ID,
                Name = x.Question_Title,
                type = x.Question_TypeCodeID,
                Lie = x.Question_Lie,
                step = x.Tbl_FormStep.FS_Display,
                ResponseCount = x.Tbl_Response.Where(xx => xx.Response_IsDelete == false).ToList().Count,
            }).ToList();

            ViewBag.FormId = id;
            ViewBag.FormDisplay = formDisplay;

            return View(_Qusetion);
        }

        [HttpGet]
        public ActionResult QuestionCreate(int id)
        {
            Model_QuestionAdd model = new Model_QuestionAdd()
            {
                ID = id
            };

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult QuestionCreate(Model_QuestionAdd model)
        {
            Tbl_Question _Question = new Tbl_Question()
            {
                Question_Title = model.Title,
                Question_Guid = Guid.NewGuid(),
                Question_FormID = model.ID,
                Question_Lie = model.Lie,
                Question_FSID = db.Tbl_FormStep.Where(a => a.FS_Guid.ToString() == model.Step).SingleOrDefault().FS_ID,
            };

            _Question.Tbl_Code = db.Tbl_Code.Where(x => x.Code_Guid.ToString() == model.Type).SingleOrDefault();

            db.Tbl_Question.Add(_Question);

            if (Convert.ToBoolean(db.SaveChanges() > 0))
            {
                TempData["TosterState"] = "success";
                TempData["TosterType"] = TosterType.Maseage;
                TempData["TosterMassage"] = "عملیات با موفقیت انجام شده";

                return RedirectToAction("Index", new { id = model.ID });
            }
            else
            {
                TempData["TosterState"] = "error";
                TempData["TosterType"] = TosterType.Maseage;
                TempData["TosterMassage"] = "خطا";

                return RedirectToAction("Index", new { id = model.ID });
            }
        }

        public ActionResult QuestionEdit(int id)
        {
            var q = db.Tbl_Question.Where(x => x.Question_ID == id).SingleOrDefault();

            if (q != null)
            {
                Model_QuestionEdit model = new Model_QuestionEdit()
                {
                    ID = q.Question_ID,
                    Title = q.Question_Title,
                    Step = q.Question_FSID.ToString(),
                    Form_ID = q.Question_FormID
                    //type = 
                };

                return PartialView(model);
            }

            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult QuestionEdit(Model_QuestionEdit model)
        {
            if (ModelState.IsValid)
            {
                Tbl_Question q = db.Tbl_Question.Where(x => x.Question_ID == model.ID).SingleOrDefault();

                if (q != null)
                {
                    q.Question_Title = model.Title;
                    q.Question_TypeCodeID = Rep_CodeGroup.Get_CodeIDWithGUID(Guid.Parse(model.Type));
                    q.Tbl_FormStep.FS_ID = Convert.ToInt32(model.Step);

                    db.Entry(q).State = EntityState.Modified;

                    if (Convert.ToBoolean(db.SaveChanges() > 0))
                    {
                        TempData["TosterState"] = "success";
                        TempData["TosterType"] = TosterType.Maseage;
                        TempData["TosterMassage"] = "عملیات با موفقیت انجام شده";

                        return RedirectToAction("Index", new { id = model.ID });
                    }
                    else
                    {
                        TempData["TosterState"] = "error";
                        TempData["TosterType"] = TosterType.Maseage;
                        TempData["TosterMassage"] = "عملیات با موفقیت انجام نشده";

                        return RedirectToAction("Index", new { id = model.ID });
                    }
                }
                else
                {
                    return HttpNotFound();
                }
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        public ActionResult QuestionDelete(int? id)
        {
            if (id != null)
            {
                Model_MessageModal model = new Model_MessageModal();

                var q = db.Tbl_Question.Where(x => x.Question_ID == id).SingleOrDefault();

                if (q != null)
                {
                    model.ID = id.Value;
                    model.Name = q.Question_Title;
                    model.Description = "آیا از حذف سوال مورد نظر اطمینان دارید ؟";

                    return PartialView(model);
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }

            return HttpNotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult QuestionDelete(Model_MessageModal model)
        {
            if (ModelState.IsValid)
            {
                var q = db.Tbl_Question.Where(x => x.Question_ID == model.ID).SingleOrDefault();

                if (q != null)
                {
                    q.Question_IsDelete = true;

                    db.Entry(q).State = EntityState.Modified;

                    if (Convert.ToBoolean(db.SaveChanges() > 0))
                    {
                        TempData["TosterState"] = "success";
                        TempData["TosterType"] = TosterType.Maseage;
                        TempData["TosterMassage"] = "عملیات با موفقیت انجام شده";

                        return RedirectToAction("Index", new { id = model.ID });
                    }
                    else
                    {
                        TempData["TosterState"] = "error";
                        TempData["TosterType"] = TosterType.Maseage;
                        TempData["TosterMassage"] = "عملیات با موفقیت انجام نشده";

                        return HttpNotFound();
                    }
                }
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        public JsonResult Get_StepList(string searchTerm, int id)
        {
            var q = db.Tbl_FormStep.Where(x => x.FS_IsDelete == false && x.FS_FormID == id).ToList();

            if (searchTerm != null)
            {
                q = q.Where(a => a.FS_Display.Contains(searchTerm)).ToList();
            }

            var md = q.Select(a => new { id = a.FS_Guid.ToString(), text = a.FS_Display });

            return Json(md, JsonRequestBehavior.AllowGet);
        }
    }
}

Wtiau.Health.Web/Controllers/ResponseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Wtiau.Health.Web.Models.Domian;
using Wtiau.Health.Web.Models.ViewModels;
using Wtiau.Health.Web.Models.Repository;
using System.Data.Entity;

namespace Wtiau.Health.Web.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class ResponseController : Controller
    {
        HealthEntities db = new HealthEntities();

        public ActionResult Index(int id, int formId, string formDisplay, string questionDisplay)
        {
            var _Response = db.Tbl_Response.Where(x => x.Tbl_Question.Question_ID == id).Select(x => new Model_ResponseList
            {
                ID = x.Response_ID,
                Order = x.Response_Order,
                Title = x.Response_Title,
                Hint = x.Response_Hint,
                IsTrue = x.Response_IsTrue,
            }).ToList();

            ViewBag.FormId = formId;
            ViewBag.FormDisplay = formDisplay;
            ViewBag.QuestionID = id;
            ViewBag.QuestionDisplay = questionDisplay;

            return View(_Response);
        }

        [HttpGet]
        public ActionResult ResponseAdd(int id)
        {
            Model_ResponseAdd model = new Model_ResponseAdd()
            {
                ID = id
            };

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult ResponseAdd(Model_ResponseAdd model)
        {
            Tbl_Response _Response = new Tbl_Response()
            {
                Response_Guid = Guid.NewGuid(),
                Response_QuestionID = model.ID,
                Response_Title = model.Title,
                Response_Order = model.Order,
                Response_IsTrue = model.IsTrue,
                Response_Hint = model.Hint,
            };

            db.Tbl_Response.Add(_Response);

            if (Convert.ToBoolean(db.SaveChanges() > 0))
            {
                TempData["TosterState"] = "success";
                TempData["TosterType"] = TosterType.Maseage;
                TempData["TosterMassage"] = "عملیات با موفقیت انجام شده";

                return RedirectToAction("Index", new { id = model.ID });
            }
            else
            {
                TempData["TosterState"] = "error";
                TempData["TosterType"] = TosterType.Maseage;
                TempData["TosterMassage"] = "خطا";

                return RedirectToAction("Index", new { id = model.ID });
            }
        }

        [HttpGet]
        public ActionResult ResponseEdit(int id)
        {
            Model_ResponseEdit model = db.Tbl_Response.Where(x => x.Response_IsDelete == false && x.Response_ID == id).Select(x => new Model_ResponseEdit
            {
                ID = id,
                Hint = x.Response_Hint,
                IsTrue = x.Response_IsTrue,
                Order = x.Response_Order,
                Title = x.Response_Title

            }).SingleOrDefault();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult ResponseEdit(Model_ResponseEdit model)
        {
            var resp = db.Tbl_Response.Where(a => a.Response_ID == model.ID).SingleOrDefault();

            resp.Response_Hint = model.Hint;
            resp.Response_IsTrue = model.IsTrue;
            resp.Response_Order = model.Order;
            resp.Response_Title = model.Title;


            db.Entry(resp).State = EntityState.Modified;

            if (Convert.ToBoolean(db.SaveChanges() > 0))
            {
                TempData["TosterState"] = "success";
                TempData["TosterType"] = TosterType.Maseage;
                TempData["TosterMassage"] = "عملیات با موفقیت انجام شده";

                return RedirectToAction("Index", new { id = resp.Response_QuestionID , formId = resp.Tbl_Question.Tbl_Form.Form_ID , formDisplay = resp.Tbl_Question.Tbl_Form.Form_Name, questionDisplay = resp.Tbl_Question.Question_Title });
            }
            else
            {
                TempData["TosterState"] = "error";
                TempData["TosterType"] = TosterType.Maseage;
                TempData["TosterMassage"] = "خطا";

                return RedirectToAction("Index", new { id = resp.Response_QuestionID, formId = resp.Tbl_Question.Tbl_Form.Form_ID, formDisplay = resp.Tbl_Question.Tbl_Form.Form_Name, questionDisplay = resp.Tbl_Question.Question_Title });
            }
        }
    }
}

Wtiau.Health.Web/Views/Question/Index.cshtml
@model IEnumerable<Wtiau.Health.Web.Models.ViewModels.Model_QusetionList>
@using Wtiau.Health.Web.Models.Repository

@{
    ViewBag.Title = "سوالات";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}


<div class="panel panel-body panel-default navigation">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Form")" data-toggle="tooltip" data-placement="auto" title="پرسش نامه ها">@ViewBag.FormDisplay</a></li>
            <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>
        </ol>
    </nav>

    @*<div class="pull-left" style="margin-left: 10px;" data-toggle='tooltip' data-placement='auto' title='برگشت به صفحه قبل'>
        <a href="@Url.Action("Index", "Form")">
            <i class="glyphicon glyphicon-arrow-left navigation-btn-icon"></i>
        </a>
    </div>*@

    @*<div class="pull-left">
        <h4 class="navigation-title"><b>@ViewBag.Title</b></h4>
    </div>*@

    <div class="pull-right">
        <a href="javascript:void(0)" onclick="Create(@ViewBag.FormId)" data-toggle='tooltip' data-placement='auto' title='افزودن سوال'>
            <i class="glyphicon glyphicon-plus navigation-btn-icon"></i>
        </a>
    </div>

</div>

<div class="panel panel-default">

    <div class="panel-body table-body" style="overflow-x:auto;">

        <table id="DateTable" class="table table-bordered table-striped table-secondary" style="width:100%;">

            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.Name)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.type)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.step)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.Lie)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.ResponseCount)</th>
                    <th scope="col" data-orderable="false">کنترل</th>
                </tr>
            </thead>

            <tbody>

                @{
                    int x = 0;
                }

                @foreach (var item in Model)
                {
                    x++;

                    <tr>
                        <td scope="row">@x</td>

                        <td scope="row">
                            <span> @Html.DisplayFor(modelItem => item.Name) </span>
                        </td>

                        <td scope="row">
                            <span> @Rep_CodeGroup.Get_CodeDisplayWithID(item.type) </span>
                        </td>

                        <td scope="row">
                            <span> @Html.DisplayFor(modelItem => item.step) </span>
                        </td>

                        <td scope="row">
                            <span> @Html.DisplayFor(modelItem => item.Lie) </span>
                        </td>

                        <td scope="row">
                            <span> @Html.DisplayFor(modelItem => item.ResponseCount) </span>
                        </td>

                        <td scope="row">
                            <a class="control btn btn-info btn-sm glyphicon glyphicon-list" data-toggle='tooltip' data-placement='auto' title='پاسخ ها' href="@Url.Action("Index", "Response", new { id = item.ID, formId = ViewBag.FormId, formDisplay = ViewBag.FormDisplay, questionDisplay = item.Name })"></a>
                            <a class="control btn btn-warning btn-sm glyphicon glyphicon-pencil" data-toggle='tooltip' data-placement='auto' title='ویرایش' href="javascript:void(0)" onclick="Edit(@item.ID)"></a>
                            <a class="control btn btn-danger btn-sm glyphicon glyphicon-trash" data-toggle='tooltip' data-placement='auto' title='حذف' href="javascript:void(0)" onclick="Delete(@item.ID)"></a>
                        </td>
                    </tr>
                }

            </tbody>

        </table>

    </div>

</div>


@Html.Partial("_Modal")

@section Modal {

    <script>

        function Delete(id) {
            $.ajax({
                url: "/Question/QuestionDelete/" + id,
                type: "Get",
                data: {}
            }).done(function (result) {
                $('#myModal').modal('show');
                $('#myModalLabel').html('حدف سوال');
                $('#myModalBody').html(result);
            });
        }

        function Create(id) {
            $.ajax({
                url: "/Question/QuestionCreate/" + id,
                type: "Get",
                data: {}
            }).done(function (result) {
                $('#myModal').modal('show');
                $('#myModalLabel').html('افزودن سوال');
                $('#myModalBody').html(result);
            });
        }

        function Edit(id) {
            $.ajax({
                url: "/Question/QuestionEdit/" + id,
                type: "Get",
                data: {}
            }).done(function (result) {
                $('#myModal').modal('show');
                $('#myModalLabel').html('ویرایش سوال');
                $('#myModalBody').html(result);
            });
        }

    </script>

}

Wtiau.Health.Web/Views/Question/QuestionAdd.cshtml
@model Wtiau.Health.Web.Models.ViewModels.Modal_QuestionAdd
@using Wtiau.Health.Web.Models.Repository




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID)

    <div class="modal-main">


        <div class="form-group">
            @Html.LabelFor(model => model.step, htmlAttributes: new { @class = "control-label" })
            @Html.DropDownListFor(model => model.step, new List<SelectListItem>() { new SelectListItem() { Value = "", Text = "لطفا کاربر مورد نظر را انتخاب کنید ..." } }, new { @class = "form-control Select2_Normal" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.type, htmlAttributes: new { @class = "control-label" })
            @Html.DropDownListFor(model => model.type, Rep_CodeGroup.Get_AllCodesWithGroupWithGUID(CodeGroup.ResponseType), new { @class = "form-control Select2_Normal" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })

            <div class="input-group">
                <span class=" input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            </div>

            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
        <div class="form-group material-switch-body">
            <label class="pull-left">دروغ سنج</label>
            <div class="material-switch pull-right">
                @Html.CheckBoxFor(model => model.Lie, htmlAttributes: new { @class = "" })
                @Html.LabelFor(model => model.Lie, htmlAttributes: new { @class = "label-success" })
            </div>
        </div>
    </div>

    <div class="">
        <button class="btn btn-danger modal-btn-Dual pull-left" type="button" data-dismiss="modal">انصراف</button>
        <button class="btn btn-success modal-btn-Dual pull-right " type="submit" name="btn-Delete">تایید</button>
    </div>
}



<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script src="~/Scripts/Plugins/jQuery.Select2/select2.js"></script>
<script src="~/Scripts/Plugins/jQuery.Select2/i18n/fa.js"></script>

<script src="~/Scripts/MyScripts/Select2_Config.js"></script>

<script>
    $(document).ready(function () {
        $("#step").select2({
            theme: "bootstrap",
            language: "fa",
            dir: "rtl",
            tokenSeparators: [',', ' '],
            minimumResultsForSearch: 6,
            placeholder: 'انتخاب کنید',
            ajax: {
                url: '/QuestionGet_StepList',
                dataType: "json",
                data: function (params) {
                    return {
                        searchTerm: params.term
                    };
                },
                processResults: function (data, params) {
                    return {
                        results: data
                    };
                }
            }
        });
    });
</script>


<script>
    $(function () {
        $("input[type='hidden']").remove();
    });
</script>

Wtiau.Health.Web/Views/Question/QuestionCreate.cshtml
@model Wtiau.Health.Web.Models.ViewModels.Model_QuestionAdd
@using Wtiau.Health.Web.Models.Repository


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID)

    <div class="modal-main">

        <div class="form-group">
            @Html.LabelFor(model => model.Step, htmlAttributes: new { @class = "control-label" })
            @Html.DropDownListFor(model => model.Step, new List<SelectListItem>() { new SelectListItem() { Value = "", Text = "لطفا کاربر مورد نظر را انتخاب کنید ..." } }, new { @class = "form-control Select2_Normal" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label" })
            @Html.DropDownListFor(model => model.Type, Rep_CodeGroup.Get_AllCodesWithGroupWithGUID(CodeGroup.ResponseType), new { @class = "form-control Select2_Normal" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })

            <div class="input-group">
                <span class=" input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            </div>

            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>

        <div class="form-group material-switch-body">
            <label class="pull-left">دروغ سنج</label>
            <div class="material-switch pull-right">
                @Html.CheckBoxFor(model => model.Lie, htmlAttributes: new { @class = "" })
                @Html.LabelFor(model => model.Lie, htmlAttributes: new { @class = "label-success" })
            </div>
        </div>

    </div>

    <div class="">
        <button class="btn btn-danger modal-btn-Dual pull-left" type="button" data-dismiss="modal">انصراف</button>
        <button class="btn btn-success modal-btn-Dual pull-right " type="submit" name="btn-Delete">تایید</button>
    </div>
}

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script src="~/Scripts/Plugins/jQuery.Select2/select2.js"></script>
<script src="~/Scripts/Plugins/jQuery.Select2/i18n/fa.js"></script>

<script src="~/Scripts/MyScripts/Select2_Config.js"></script>

<script>
    $(document).ready(function () {
        $("#Step").select2({
            theme: "bootstrap",
            language: "fa",
            dir: "rtl",
            tokenSeparators: [',', ' '],
            minimumResultsForSearch: 6,
            placeholder: 'انتخاب کنید',
            ajax: {
                url: '/Question/Get_StepList/',
                dataType: "json",
                data: function (params) {
                    return {
                        searchTerm: params.term,
                        id: @Model.ID,
                    };
                },
                processResults: function (data, params) {
                    return {
                        results: data
                    };
                }
            }
        });
    });
</script>

<script>
    $(function () {
        $("input[type='hidden']").remove();
    });
</script>

Wtiau.Health.Web/Views/Question/QuestionDelete.cshtml
@model Wtiau.Health.Web.Models.ViewModels.Model_MessageModal


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID)

    <br />
    <h4 class="text-center">@Model.Description</h4>
    <br />

    <div class="">
        <button class="btn btn-danger modal-btn-Dual pull-left" type="button" data-dismiss="modal">انصراف</button>
        <button class="btn btn-success modal-btn-Dual pull-right " type="submit" name="btn-Delete">تایید</button>
    </div>
}


<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Wtiau.Health.Web/Views/Question/QuestionEdit.cshtml
@model Wtiau.Health.Web.Models.ViewModels.Model_QuestionEdit
@using Wtiau.Health.Web.Models.Repository


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID)

    <div class="modal-main">

        <div class="form-group">
            @Html.LabelFor(model => model.Step, htmlAttributes: new { @class = "control-label" })
            @Html.DropDownListFor(model => model.Step, new Rep_SelectItems().Get_AllStep(Model.Form_ID), new { @class = "form-control Select2_Normal" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label" })
            @Html.DropDownListFor(model => model.Type, Rep_CodeGroup.Get_AllCodesWithGroupWithGUID(CodeGroup.ResponseType), new { @class = "form-control Select2_Normal" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })

            <div class="input-group">
                <span class=" input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            </div>

            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>

        <div class="form-group material-switch-body">
            <label class="pull-left">دروغ سنج</label>
            <div class="material-switch pull-right">
                @Html.CheckBoxFor(model => model.Lie, htmlAttributes: new { @class = "" })
                @Html.LabelFor(model => model.Lie, htmlAttributes: new { @class = "label-success" })
            </div>
        </div>

    </div>

    <div class="">
        <button class="btn btn-danger modal-btn-Dual pull-left" type="button" data-dismiss="modal">انصراف</button>
        <button class="btn btn-success modal-btn-Dual pull-right " type="submit" name="btn-Delete">تایید</button>
    </div>
}


<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script src="~/Scripts/Plugins/jQuery.Select2/select2.js"></script>
<script src="~/Scripts/Plugins/jQuery.Select2/i18n/fa.js"></script>

<script src="~/Scripts/MyScripts/Select2_Config.js"></script>

@*<script>
    $(document).ready(function () {
        $("#Step").select2({
            theme: "bootstrap",
            language: "fa",
            dir: "rtl",
            tokenSeparators: [',', ' '],
            minimumResultsForSearch: 6,
            placeholder: 'انتخاب کنید',
            ajax: {
                url: '/Question/Get_StepList/',
                dataType: "json",
                data: function (params) {
                    return {
                        searchTerm: params.term,
                        id: @Model.ID,
                    };
                },
                processResults: function (data, params) {
                    return {
                        results: data
                    };
                }
            }
        });
    });
</script>*@

<script>
    $(function () {
        $("input[type='hidden']").remove();
    });
</script>