Wtiau.Health.Web/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Wtiau.Health.Web.Models.Domian;
using Wtiau.Health.Web.Models.ViewModels;
using Wtiau.Health.Web.Models.Repository;
using System.Data.Entity;
using System.Net;

namespace Wtiau.Health.Web.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class QuestionController : Controller
    {
        HealthEntities db = new HealthEntities();

        public ActionResult Index(int id, string formDisplay)
        {
            var _Qusetion = db.Tbl_Question.Where(x => x.Question_IsDelete == false && x.Tbl_FormStep.FS_FormID == id).Select(x => new Model_QusetionList
            {
                ID = x.Question_ID,
                Name = x.Question_Title,
                type = x.Question_TypeCodeID,
                Lie = x.Question_Lie,
                step = x.Tbl_FormStep.FS_Display,
                ResponseCount = x.Tbl_Response.Where(xx => xx.Response_IsDelete == false).ToList().Count,
            }).ToList();

            ViewBag.FormId = id;
            ViewBag.FormDisplay = formDisplay;

            return View(_Qusetion);
        }

        [HttpGet]
        public ActionResult QuestionCreate(int id)
        {
            Model_QuestionAdd model = new Model_QuestionAdd()
            {
                ID = id
            };

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult QuestionCreate(Model_QuestionAdd model)
        {
            Tbl_Question _Question = new Tbl_Question()
            {
                Question_Title = model.Title,
                Question_Guid = Guid.NewGuid(),
                Question_FormID = model.ID,
                Question_Lie = model.Lie,
                Question_FSID = db.Tbl_FormStep.Where(a => a.FS_Guid.ToString() == model.Step).SingleOrDefault().FS_ID,
            };

            _Question.Tbl_Code = db.Tbl_Code.Where(x => x.Code_Guid.ToString() == model.Type).SingleOrDefault();

            db.Tbl_Question.Add(_Question);

            if (Convert.ToBoolean(db.SaveChanges() > 0))
            {
                TempData["TosterState"] = "success";
                TempData["TosterType"] = TosterType.Maseage;
                TempData["TosterMassage"] = "عملیات با موفقیت انجام شده";

                return RedirectToAction("Index", new { id = model.ID });
            }
            else
            {
                TempData["TosterState"] = "error";
                TempData["TosterType"] = TosterType.Maseage;
                TempData["TosterMassage"] = "خطا";

                return RedirectToAction("Index", new { id = model.ID });
            }
        }

        public ActionResult QuestionEdit(int id)
        {
            var q = db.Tbl_Question.Where(x => x.Question_ID == id).SingleOrDefault();

            if (q != null)
            {
                Model_QuestionEdit model = new Model_QuestionEdit()
                {
                    ID = q.Question_ID,
                    Title = q.Question_Title,
                    Step = q.Question_FSID.ToString(),
                    Form_ID = q.Question_FormID
                    //type = 
                };

                return PartialView(model);
            }

            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult QuestionEdit(Model_QuestionEdit model)
        {
            if (ModelState.IsValid)
            {
                Tbl_Question q = db.Tbl_Question.Where(x => x.Question_ID == model.ID).SingleOrDefault();

                if (q != null)
                {
                    q.Question_Title = model.Title;
                    q.Question_TypeCodeID = Rep_CodeGroup.Get_CodeIDWithGUID(Guid.Parse(model.Type));
                    q.Tbl_FormStep.FS_ID = Convert.ToInt32(model.Step);

                    db.Entry(q).State = EntityState.Modified;

                    if (Convert.ToBoolean(db.SaveChanges() > 0))
                    {
                        TempData["TosterState"] = "success";
                        TempData["TosterType"] = TosterType.Maseage;
                        TempData["TosterMassage"] = "عملیات با موفقیت انجام شده";

                        return RedirectToAction("Index", new { id = model.ID });
                    }
                    else
                    {
                        TempData["TosterState"] = "error";
                        TempData["TosterType"] = TosterType.Maseage;
                        TempData["TosterMassage"] = "عملیات با موفقیت انجام نشده";

                        return RedirectToAction("Index", new { id = model.ID });
                    }
                }
                else
                {
                    return HttpNotFound();
                }
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        public ActionResult QuestionDelete(int? id)
        {
            if (id != null)
            {
                Model_MessageModal model = new Model_MessageModal();

                var q = db.Tbl_Question.Where(x => x.Question_ID == id).SingleOrDefault();

                if (q != null)
                {
                    model.ID = id.Value;
                    model.Name = q.Question_Title;
                    model.Description = "آیا از حذف سوال مورد نظر اطمینان دارید ؟";

                    return PartialView(model);
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }

            return HttpNotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult QuestionDelete(Model_MessageModal model)
        {
            if (ModelState.IsValid)
            {
                var q = db.Tbl_Question.Where(x => x.Question_ID == model.ID).SingleOrDefault();

                if (q != null)
                {
                    q.Question_IsDelete = true;

                    db.Entry(q).State = EntityState.Modified;

                    if (Convert.ToBoolean(db.SaveChanges() > 0))
                    {
                        TempData["TosterState"] = "success";
                        TempData["TosterType"] = TosterType.Maseage;
                        TempData["TosterMassage"] = "عملیات با موفقیت انجام شده";

                        return RedirectToAction("Index", new { id = model.ID });
                    }
                    else
                    {
                        TempData["TosterState"] = "error";
                        TempData["TosterType"] = TosterType.Maseage;
                        TempData["TosterMassage"] = "عملیات با موفقیت انجام نشده";

                        return HttpNotFound();
                    }
                }
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        public JsonResult Get_StepList(string searchTerm, int id)
        {
            var q = db.Tbl_FormStep.Where(x => x.FS_IsDelete == false && x.FS_FormID == id).ToList();

            if (searchTerm != null)
            {
                q = q.Where(a => a.FS_Display.Contains(searchTerm)).ToList();
            }

            var md = q.Select(a => new { id = a.FS_Guid.ToString(), text = a.FS_Display });

            return Json(md, JsonRequestBehavior.AllowGet);
        }
    }
}

Wtiau.Health.Web/Controllers/StepController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Wtiau.Health.Web.Models.Domian;
using Wtiau.Health.Web.Models.ViewModels;

namespace Wtiau.Health.Web.Controllers
{
    [Authorize(Roles = "Admin, SuperAdmin")]
    public class StepController : Controller
    {
        HealthEntities db = new HealthEntities();

        public ActionResult Index(int id, string formDisplay)
        {
            var _step = db.Tbl_FormStep.Where(x => x.FS_IsDelete == false && x.FS_FormID == id).Select(x => new Model_FormStepList
            {
                ID = x.FS_ID,
                Name = x.FS_Name,
                Display = x.FS_Display,
                QuestionCount = db.Tbl_FormStep.Where(xx => xx.FS_FormID == id).FirstOrDefault().Tbl_Question.Where(xx => xx.Question_IsDelete == false).ToList().Count,
                Order = x.FS_Order
            }).ToList();

            ViewBag.FormDisplay = formDisplay;
            ViewBag.ID = id;

            return View(_step);
        }

    }
}

Wtiau.Health.Web/Views/Form/AddStep.cshtml
@model Wtiau.Health.Web.Models.ViewModels.Model_FormStepAdd


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID)

<div class="modal-main">


    <div class="form-group">
        @Html.LabelFor(model => model.Display, htmlAttributes: new { @class = "control-label" })

        <div class="input-group">
            <span class=" input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
            @Html.EditorFor(model => model.Display, new { htmlAttributes = new { @class = "form-control" } })
        </div>

        @Html.ValidationMessageFor(model => model.Display, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })

        <div class="input-group">
            <span class=" input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
        </div>

        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Order, htmlAttributes: new { @class = "control-label" })

        <div class="input-group">
            <span class=" input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
            @Html.EditorFor(model => model.Order, new { htmlAttributes = new { @class = "form-control" } })
        </div>

        @Html.ValidationMessageFor(model => model.Order, "", new { @class = "text-danger" })
    </div>

</div>

    <div class="">
        <button class="btn btn-danger modal-btn-Dual pull-left" type="button" data-dismiss="modal">انصراف</button>
        <button class="btn btn-success modal-btn-Dual pull-right " type="submit" name="btn-Delete">تایید</button>
    </div>
}


<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Wtiau.Health.Web/Views/Form/CreateForm.cshtml
@model Wtiau.Health.Web.Models.ViewModels.Model_FormCreate


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID)

    <div class="modal-main">

        <div class="form-group">
            @Html.LabelFor(model => model.Course, htmlAttributes: new { @class = "control-label" })

            <div class="input-group">
                <span class=" input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                @Html.EditorFor(model => model.Course, new { htmlAttributes = new { @class = "form-control" } })
            </div>

            @Html.ValidationMessageFor(model => model.Course, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Form_Display, htmlAttributes: new { @class = "control-label" })

            <div class="input-group">
                <span class=" input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                @Html.EditorFor(model => model.Form_Display, new { htmlAttributes = new { @class = "form-control" } })
            </div>

            @Html.ValidationMessageFor(model => model.Form_Display, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Form_Name, htmlAttributes: new { @class = "control-label" })

            <div class="input-group">
                <span class=" input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                @Html.EditorFor(model => model.Form_Name, new { htmlAttributes = new { @class = "form-control" } })
            </div>

            @Html.ValidationMessageFor(model => model.Form_Name, "", new { @class = "text-danger" })
        </div>

    </div>

    <div class="">
        <button class="btn btn-danger modal-btn-Dual pull-left" type="button" data-dismiss="modal">انصراف</button>
        <button class="btn btn-success modal-btn-Dual pull-right " type="submit" name="btn-Delete">تایید</button>
    </div>
}


<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Wtiau.Health.Web/Views/Form/DeleteForm.cshtml
@model Wtiau.Health.Web.Models.ViewModels.Model_MessageModal


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID)

    <br />
    <h4 class="text-center">@Model.Description</h4>
    <br />

    <div class="">
        <button class="btn btn-danger modal-btn-Dual pull-left" type="button" data-dismiss="modal">انصراف</button>
        <button class="btn btn-success modal-btn-Dual pull-right " type="submit" name="btn-Delete">تایید</button>
    </div>
}


<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Wtiau.Health.Web/Views/Form/EditForm.cshtml
@model Wtiau.Health.Web.Models.ViewModels.Model_FormEdit
@using Wtiau.Health.Web.Models.Repository

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID)

    <div class="modal-main">

        <div class="form-group">
            @Html.LabelFor(model => model.Course, htmlAttributes: new { @class = "control-label" })
            @Html.DropDownListFor(model => model.Course, new Rep_SelectItems().Get_AllCourse(), new { @class = "form-control Select2_Normal" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Form_Display, htmlAttributes: new { @class = "control-label" })

            <div class="input-group">
                <span class=" input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                @Html.EditorFor(model => model.Form_Display, new { htmlAttributes = new { @class = "form-control" } })
            </div>

            @Html.ValidationMessageFor(model => model.Form_Display, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Form_Name, htmlAttributes: new { @class = "control-label" })

            <div class="input-group">
                <span class=" input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                @Html.EditorFor(model => model.Form_Name, new { htmlAttributes = new { @class = "form-control" } })
            </div>

            @Html.ValidationMessageFor(model => model.Form_Name, "", new { @class = "text-danger" })
        </div>

    </div>

    <div class="">
        <button class="btn btn-danger modal-btn-Dual pull-left" type="button" data-dismiss="modal">انصراف</button>
        <button class="btn btn-success modal-btn-Dual pull-right " type="submit" name="btn-Delete">تایید</button>
    </div>
}


<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script src="~/Scripts/Plugins/jQuery.Select2/select2.js"></script>
<script src="~/Scripts/Plugins/jQuery.Select2/i18n/fa.js"></script>

<script src="~/Scripts/MyScripts/Select2_Config.js"></script>

<script>
    $(document).ready(function () {
        $("#Course").select2({
            theme: "bootstrap",
            language: "fa",
            dir: "rtl",
            tokenSeparators: [',', ' '],
            minimumResultsForSearch: 6,
            placeholder: 'انتخاب کنید',
            ajax: {
                url: '/Form/Get_CourseList',
                dataType: "json",
                data: function (params) {
                    return {
                        searchTerm: params.term
                    };
                },
                processResults: function (data, params) {
                    return {
                        results: data
                    };
                }
            }
        });
    });
</script>

Wtiau.Health.Web/Views/Form/Index.cshtml
@model IEnumerable<Wtiau.Health.Web.Models.ViewModels.Model_FormList>

@{
    ViewBag.Title = "لیست پرسش نامه ها";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}


<div class="panel panel-body panel-default navigation">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">پرسش نامه ها</li>
        </ol>
    </nav>

    @*<div class="pull-left">
        <h4 class="navigation-title"><b>@ViewBag.Title</b></h4>
    </div>*@

    <div class="pull-right">
        <a href="javascript:void(0)" onclick="Create()" data-toggle='tooltip' data-placement='auto' title='افزودن پرسش نامه'>
            <i class="glyphicon glyphicon-plus navigation-btn-icon"></i>
        </a>
    </div>

</div>

<div class="panel panel-default">

    <div class="panel-body table-body" style="overflow-x:auto;">

        <table id="DateTable" class="table table-bordered table-striped table-secondary" style="width:100%;">

            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.Form_Name)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.Form_QuestionCount)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.Form_StepCount)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.Form_CreateDate)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.Form_IsActive)</th>
                    <th scope="col" data-orderable="false">کنترل</th>
                </tr>
            </thead>

            <tbody>

                @{
                    int x = 0;
                }

                @foreach (var item in Model)
                {
                    x++;

                    <tr>
                        <td scope="row">@x</td>
                        <td scope="row">
                            <span> @Html.DisplayFor(modelItem => item.Form_Name) </span>
                        </td>
                        <td scope="row">
                            <span> @Html.DisplayFor(modelItem => item.Form_QuestionCount) </span>
                        </td>
                        <td scope="row">
                            <span> @Html.DisplayFor(modelItem => item.Form_StepCount) </span>
                        </td>
                        <td scope="row">
                            <span> @Html.DisplayFor(modelItem => item.Form_CreateDate) </span>
                        </td>
                        <td scope="row">
                            <span> @(item.Form_IsActive ? "فعال" : "غیر فعال") </span>
                        </td>

                        <td scope="row">
                            <a class="control btn btn-primary btn-sm glyphicon glyphicon-th-list" data-toggle='tooltip' data-placement='auto' title='مراحل' href="@Url.Action("Index", "Step", new { id = item.ID, formDisplay = item.Form_Name })"></a>
                            <a class="control btn btn-success btn-sm glyphicon glyphicon-plus" data-toggle='tooltip' data-placement='auto' title='افزودن مرحله' href="javascript:void(0)" onclick="AddStep(@item.ID)"></a>
                            <a class="control btn btn-info btn-sm glyphicon glyphicon-list" data-toggle='tooltip' data-placement='auto' title='سوالات' href="@Url.Action("Index", "Question", new { id = item.ID, formDisplay = item.Form_Name })"></a>
                            <a class="control btn btn-warning btn-sm glyphicon glyphicon-pencil" data-toggle='tooltip' data-placement='auto' title='ویرایش' href="javascript:void(0)" onclick="Edit(@item.ID)"></a>
                            <a class="control btn wtiau-btn-wtiau btn-sm glyphicon glyphicon-ok" data-toggle='tooltip' data-placement='auto' title='تغییر وضعیت نمایش' href="javascript:void(0)" onclick="SetActiveness(@item.ID)"></a>
                            <a class="control btn btn-danger btn-sm glyphicon glyphicon-trash" data-toggle='tooltip' data-placement='auto' title='حذف' href="javascript:void(0)" onclick="Delete(@item.ID)"></a>
                        </td>
                    </tr>
                }

            </tbody>

        </table>

    </div>

</div>


@Html.Partial("_Modal")


@section Modal {

    <script>

        function Delete(id) {
            $.ajax({
                url: "/Form/DeleteForm/" + id,
                type: "Get",
                data: {}
            }).done(function (result) {
                $('#myModal').modal('show');
                $('#myModalLabel').html('حدف پرسش نامه');
                $('#myModalBody').html(result);
            });
        }

        function Edit(id) {
            $.ajax({
                url: "/Form/EditForm/" + id,
                type: "Get",
                data: {}
            }).done(function (result) {
                $('#myModal').modal('show');
                $('#myModalLabel').html('ویرایش پرسش نامه');
                $('#myModalBody').html(result);
            });
        }

        function Create() {
            $.ajax({
                url: "/Form/CreateForm",
                type: "Get",
                data: {}
            }).done(function (result) {
                $('#myModal').modal('show');
                $('#myModalLabel').html('افزودن پرسش نامه');
                $('#myModalBody').html(result);
            });
        }

        function AddStep(id) {
            $.ajax({
                url: "/Form/AddStep/" + id,
                type: "Get",
                data: {}
            }).done(function (result) {
                $('#myModal').modal('show');
                $('#myModalLabel').html('افزودن مرحله');
                $('#myModalBody').html(result);
            });
        }

        function SetActiveness(id) {
            $.ajax({
                url: "/Form/SetActiveness/" + id,
                type: "Get",
                data: {}
            }).done(function (result) {
                $('#myModal').modal('show');
                $('#myModalLabel').html('تغییر وضعیت نمایش');
                $('#myModalBody').html(result);
            });
        }

    </script>

}