Wtiau.Health.Web/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Wtiau.Health.Web.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        [Authorize(Roles ="Admin,SuperAdmin")]
        public ActionResult Index()
        {
            return View();
        }
    }
}

Wtiau.Health.Web/Controllers/PortalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Wtiau.Health.Web.Controllers
{
    public class PortalController : Controller
    {
        // GET: Portal
        public ActionResult Index()
        {

            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("PortalLogin", "Account");
            }
            return View();
        }
    }
}

Wtiau.Health.Web/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Wtiau.Health.Web.Controllers
{
    public class ReportController : Controller
    {
        // GET: Report
        public ActionResult Index()
        {
            return View();
        }
    }
}

Wtiau.Health.Web/Controllers/SettingController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Wtiau.Health.Web.Models.Domian;
using Wtiau.Health.Web.Models.ViewModels;

namespace Wtiau.Health.Web.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class SettingController : Controller
    {
        readonly HealthEntities db = new HealthEntities();

        public ActionResult Index()
        {
            return View();
        }

        #region Student



        #endregion

        #region Role

        public ActionResult Role_List()
        {
            var model = db.Tbl_Role.Where(x => x.Role_IsDelete == false).Select(x => new Model_RoleList
            {
                ID = x.Role_ID,
                Display = x.Role_Display,
                Name = x.Role_Name,
                Level = x.Role_Level

            }).ToList();

            return View(model);
        }

        #endregion

        #region User

        public ActionResult User_List()
        {
            var model = db.Tbl_Login.Where(x => x.Login_IsDelete == false).Select(x => new Model_UserList
            {
                ID = x.Login_ID,
                Family = x.Login_Family,
                Name = x.Login_Name,
                Role = x.Tbl_Role.Role_Display,
                Email = x.Login_Email,
                Mobile = x.Login_Mobile

            }).ToList();

            return View(model);
        }

        public ActionResult User_Add()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult User_Add(Model_UserAdd model)
        {
            if (ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Tbl_Login _Login = new Tbl_Login
            {
                Login_Guid = Guid.NewGuid(),
                Login_Email = model.Email,
                Login_Name = model.Name,
                Login_Family = model.Family,
                Login_Mobile = model.Mobile,
                Login_RoleID = model.Role,
                Login_CreateDate = DateTime.Now,
                Login_Modify = DateTime.Now
            };

            var Salt = Guid.NewGuid().ToString("N");
            var SaltPassword = model.Password + Salt;
            var SaltPasswordBytes = Encoding.UTF8.GetBytes(SaltPassword);
            var SaltPasswordHush = Convert.ToBase64String(SHA512.Create().ComputeHash(SaltPasswordBytes));

            _Login.Login_PasswordHash = SaltPasswordHush;
            _Login.Login_PasswordSalt = Salt;

            db.Tbl_Login.Add(_Login);

            if (Convert.ToBoolean(db.SaveChanges() > 0))
            {
                TempData["TosterState"] = "success";
                TempData["TosterType"] = TosterType.Maseage;
                TempData["TosterMassage"] = "کاربر جدید با موفقیت اضافه شد.";

                return RedirectToAction("User_List");
            }
            else
            {
                TempData["TosterState"] = "error";
                TempData["TosterType"] = TosterType.Maseage;
                TempData["TosterMassage"] = "کاربر جدید با موفقیت اضافه نشد.";

                return View();
            }
        }

        public ActionResult User_Edit(int? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (db.Tbl_Login.Any(a => a.Login_ID == id))
            {
                var model = db.Tbl_Login.Where(a => a.Login_ID == id).Select(x => new Model_UserEdit
                {
                    ID = x.Login_ID,
                    Family = x.Login_Family,
                    Name = x.Login_Name,
                    Role = x.Login_RoleID,
                    Email = x.Login_Email,
                    Mobile = x.Login_Mobile
                    
                }).SingleOrDefault();

                return PartialView(model);
            }
            else
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        public ActionResult User_Edit(Model_UserEdit model)
        {
            if (ModelState.IsValid)
            {
                var _Login = db.Tbl_Login.Where(x => x.Login_ID == model.ID && !x.Login_IsDelete).SingleOrDefault();

                if (_Login != null)
                {
                    _Login.Login_Name = model.Name;
                    _Login.Login_Family = model.Family;
                    _Login.Login_Mobile = model.Mobile;
                    _Login.Login_Email = model.Email;
                    _Login.Login_RoleID = model.Role;
                    _Login.Login_Modify = DateTime.Now;

                    db.Entry(_Login).State = EntityState.Modified;

                    if (Convert.ToBoolean(db.SaveChanges() > 0))
                    {
                        TempData["TosterState"] = "success";
                        TempData["TosterType"] = TosterType.Maseage;
                        TempData["TosterMassage"] = "کاربر مورد نظر با موفقیت ویرایش شد.";
                    }
                    else
                    {
                        TempData["TosterState"] = "error";
                        TempData["TosterType"] = TosterType.Maseage;
                        TempData["TosterMassage"] = "کاربر مورد نظر با موفقیت ویرایش نشد.";
                    }

                    return RedirectToAction("User_List");
                }

                return HttpNotFound();
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        public ActionResult User_Delete(int? id)
        {
            if (id.HasValue)
            {
                Model_MessageModal model = new Model_MessageModal();

                var _Login = db.Tbl_Login.Where(x => x.Login_ID == id).SingleOrDefault();

                if (_Login != null)
                {
                    model.ID = id.Value;
                    model.Name = _Login.Login_Name + " " + _Login.Login_Family;
                    model.Description = "آیا از حذف کاربر مورد نظر اطمینان دارید ؟";

                    return PartialView(model);
                }

                return HttpNotFound();
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [HttpPost]
        public ActionResult User_Delete(Model_MessageModal model)
        {
            if (ModelState.IsValid)
            {
                var _Login = db.Tbl_Login.Where(x => x.Login_ID == model.ID && !x.Login_IsDelete).SingleOrDefault();

                if (_Login != null)
                {
                    _Login.Login_IsDelete = true;

                    db.Entry(_Login).State = EntityState.Modified;

                    if (Convert.ToBoolean(db.SaveChanges() > 0))
                    {
                        TempData["TosterState"] = "success";
                        TempData["TosterType"] = TosterType.Maseage;
                        TempData["TosterMassage"] = "کاربر مورد نظر با موفقیت حذف شد.";
                    }
                    else
                    {
                        TempData["TosterState"] = "error";
                        TempData["TosterType"] = TosterType.Maseage;
                        TempData["TosterMassage"] = "کاربر مورد نظر با موفقیت حذف نشد.";
                    }

                    return RedirectToAction("User_List");
                }
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        #endregion

    }
}

Wtiau.Health.Web/Controllers/TurnController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Wtiau.Health.Web.Models.Domian;
using Wtiau.Health.Web.Models.ViewModels;

namespace Wtiau.Health.Web.Controllers
{
    public class TurnController : Controller
    {
        HealthEntities db = new HealthEntities();

        // GET: Turn
        public ActionResult Index()
        {
            var _turn = db.Tbl_Turn.Where(x => x.Turn_IsDelete == false).Select(x => new Model_TurnList
            {
                Titel = x.Turn_Name,
                Descripton = x.Turn_Description,
                Activeness = x.Turn_IsActive,
                ID = x.Turn_ID,

            }).ToList();

            return View(_turn);
        }

        [HttpGet]
        public ActionResult TurnAdd()
        {

            return PartialView();
        }

        [HttpPost]
        public ActionResult TurnAdd(Model_TurnAdd model)
        {
            Tbl_Turn _Turn = new Tbl_Turn()
            {
                Turn_Guid = Guid.NewGuid(),
                Turn_Name = model.Titel,
                Turn_Description = model.Descripton,
                Turn_IsActive = model.Activeness,
            };

            db.Tbl_Turn.Add(_Turn);

            if (Convert.ToBoolean(db.SaveChanges() > 0))
            {
                TempData["TosterState"] = "success";
                TempData["TosterType"] = TosterType.Maseage;
                TempData["TosterMassage"] = "عملیات با موفقیت انجام شده";

                return RedirectToAction("Index");
            }
            else
            {
                TempData["TosterState"] = "error";
                TempData["TosterType"] = TosterType.Maseage;
                TempData["TosterMassage"] = "خطا";

                return RedirectToAction("Index");

            }

        }

        [HttpGet]
        public ActionResult TurnEdit(int id)
        {
            Model_TurnEdit model = db.Tbl_Turn.Where(a => a.Turn_ID == id).Select(a => new Model_TurnEdit
            {
                ID = a.Turn_ID,
                Activeness = a.Turn_IsActive,
                Descripton = a.Turn_Description,
                Titel = a.Turn_Name,
            }).SingleOrDefault();


            return PartialView(model);
        }

        [HttpPost]
        public ActionResult TurnEdit(Model_TurnEdit model)
        {
            Tbl_Turn _Turn = db.Tbl_Turn.Where(a => a.Turn_ID == model.ID).SingleOrDefault();

            if (_Turn != null)
            {
                _Turn.Turn_Name = model.Titel;
                _Turn.Turn_IsActive = model.Activeness;
                _Turn.Turn_Description = model.Descripton;


                db.Entry(_Turn).State = EntityState.Modified;

                if (Convert.ToBoolean(db.SaveChanges() > 0))
                {
                    TempData["TosterState"] = "success";
                    TempData["TosterType"] = TosterType.Maseage;
                    TempData["TosterMassage"] = "عملیات با موفقیت انجام شده";

                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["TosterState"] = "error";
                    TempData["TosterType"] = TosterType.Maseage;
                    TempData["TosterMassage"] = "خطا";

                    return RedirectToAction("Index");

                }
            }

            return View();
        }


        [HttpGet]
        public ActionResult TurnDelete(int? id)
        {
            if (id.HasValue)
            {
                Model_MessageModal model = new Model_MessageModal();

                var q = db.Tbl_Turn.Where(x => x.Turn_ID == id).SingleOrDefault();

                if (q != null)
                {
                    model.ID = id.Value;
                    model.Name = q.Turn_Name;
                    model.Description = "آیا از حذف نوبت مورد نظر اطمینان دارید ؟";

                    return PartialView(model);
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }

            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult TurnDelete(Model_MessageModal model)
        {

            if (ModelState.IsValid)
            {
                var q = db.Tbl_Turn.Where(x => x.Turn_ID == model.ID).SingleOrDefault();

                if (q != null)
                {
                    q.Turn_IsDelete = true;

                    db.Entry(q).State = EntityState.Modified;

                    if (Convert.ToBoolean(db.SaveChanges() > 0))
                    {
                        TempData["TosterState"] = "success";
                        TempData["TosterType"] = TosterType.Maseage;
                        TempData["TosterMassage"] = "عملیات با موفقیت انجام شده";

                        return RedirectToAction("Index", new { id = model.ID });
                    }
                    else
                    {
                        TempData["TosterState"] = "error";
                        TempData["TosterType"] = TosterType.Maseage;
                        TempData["TosterMassage"] = "عملیات با موفقیت انجام نشده";

                        return HttpNotFound();
                    }
                }
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
    }
}

Wtiau.Health.Web/Views/Shared/_AsideAdmin.cshtml
<ul class="navbar nav aside-panel">

    <li>
        <img src="~/Content/Images/logo-uni.png" alt="Logo" class="img-responsive img-rounded img-logo" style="height:200px;">
        <a href="@Url.Action("index", "Dashboard")">
            <i class="glyphicon glyphicon-dashboard"></i>
            داشبورد
        </a>
    </li>

    <li data-toggle="collapse" data-target="#sub-menu-site">

        <a href="javascript:void(0)">
            <i class="glyphicon glyphicon-book"></i>
            مدیرت دانشجویان
            <i class="glyphicon glyphicon-chevron-right pull-right gly-rotate-90"></i>
        </a>

        <ul class="collapse nav aside-sub-panel " id="sub-menu-site">
            <li>
                <a href="@Url.Action("Index", "Student")">
                    <i class="glyphicon glyphicon-book"></i>
                    لیست دانشجویان
                </a>
            </li>

            @*<li>
                    <a href="#">
                        <i class="glyphicon glyphicon-book"></i>
                        شرکت کننده در نظرسنجی
                    </a>
                </li>

                <li>
                    <a href="#">
                        <i class="glyphicon glyphicon-book"></i>
                        شرکت نکرده در نظرسنجی
                    </a>
                </li>*@

        </ul>

    </li>



    <li>
        <a href="@Url.Action("index","Turn")">
            <i class="glyphicon glyphicon-list"></i>
            نوبت دهی
        </a>
    </li>

    <li>
        <a href="@Url.Action("Index", "Form")">
            <i class="glyphicon glyphicon-list"></i>
            پرسش نامه ها
        </a>
    </li>

    @*<li>
            <a href="@Url.Action("Excel", "File")">
                <i class="glyphicon glyphicon-list"></i>
                فایل
            </a>
        </li>*@

    <li>
        <a href="@Url.Action("index","Report")">
            <i class="glyphicon glyphicon-book"></i>
            گزارشات
        </a>

    </li>

    <li>
        <a href="@Url.Action("index","Setting")">
            <i class="glyphicon glyphicon-book"></i>
            تنظیمات سامانه
        </a>

    </li>

</ul>

Wtiau.Health.Web/Views/Shared/_Dashboard.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>داشبورد | @ViewBag.Title</title>

    <link href="~/Content/Plugins/Boostrap3/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Fonts/font awesome/css/fontawesome-all.min.css" rel="stylesheet" />
    <link href="~/Content/Css/font.css" rel="stylesheet" />

    <link href="~/Content/Css/MyCss/Dashboard.css" rel="stylesheet" />

    <link href="~/Scripts/Plugins/DataTables-1.10.18/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Plugins/jQuery.Select2/select2.min.css" rel="stylesheet" />
    <link href="~/Content/Plugins/jQuery.Select2/select2-bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Plugins/jQuery.toastr/custom/toastr.css" rel="stylesheet" />
    <link href="~/Content/Plugins/MaterialDesignSwitch/MaterialDesignSwitch.css" rel="stylesheet" />

    @RenderSection("Styles", false)

</head>
<body>

    <header class="main-header container-fluid  navbar-fixed-top">

        <div class="row">

            <div class="col-md-3  navHeader">
                <img src="~/Content/Images/LogoTitel.png" style="height:45px;margin-top:-8px" />
            </div>
            <nav class="col-md-9  navbar navbar-inverse " style="border-radius:0;">

                @Html.Partial("_Nav")

            </nav>
        </div>

    </header>

    <main class="Main-Config">
        <aside class="aside-Config">
            @Html.Partial("_AsideAdmin")
        </aside>
        <section class="section-Config">
            @RenderBody()
        </section>

    </main>

    <footer></footer>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/Scripts/Plugins/Boostrap3/bootstrap.min.js"></script>
    <script src="~/Scripts/Plugins/DataTables-1.10.18/js/jquery.dataTables.js"></script>
    <script src="~/Scripts/Plugins/DataTables-1.10.18/js/dataTables.bootstrap.min.js"></script>
    <script src="~/Scripts/Plugins/jQuery.slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/Scripts/Plugins/jQuery.Select2/select2.js"></script>
    <script src="~/Scripts/Plugins/jQuery.Select2/i18n/fa.js"></script>
    <script src="~/Scripts/Plugins/jQuery.toastr/toastr.min.js"></script>
    <script src="~/Scripts/Plugins/jQuery.slimscroll/jquery.slimscroll.min.js"></script>

    <script src="~/Scripts/MyScripts/DataTabels_Config.js"></script>
    <script src="~/Scripts/MyScripts/Toastr_Config.js"></script>
    <script src="~/Scripts/MyScripts/Select2_Config.js"></script>

    @Html.Partial("_Toster")

    @RenderSection("Scripts", false)

    @RenderSection("Modal", false)

    <script src="~/Scripts/modernizr-2.8.3.js"></script>

</body>
</html>

Wtiau.Health.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Wtiau.Health.Web/Views/Shared/_Master.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="~/Content/Plugins/Boostrap3/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Fonts/font awesome/css/fontawesome-all.min.css" rel="stylesheet" />
    <link href="~/Content/Css/font.css" rel="stylesheet" />

    <link href="~/Content/Css/MyCss/Dashboard.css" rel="stylesheet" />

    <link href="~/Scripts/Plugins/DataTables-1.10.18/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Plugins/jQuery.Select2/select2.min.css" rel="stylesheet" />
    <link href="~/Content/Plugins/jQuery.Select2/select2-bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Plugins/jQuery.toastr/custom/toastr.css" rel="stylesheet" />
    <link href="~/Content/Plugins/MaterialDesignSwitch/MaterialDesignSwitch.css" rel="stylesheet" />

    @RenderSection("Styles", false)

</head>
<body>

    <header class="main-header container-fluid  navbar-fixed-top">

        <div class="row">

            <div class="col-md-3  navHeader">
                <img src="~/Content/Images/LogoTitel.png" style="height:45px;margin-top:-8px" />
            </div>
            <nav class="col-md-9  navbar navbar-inverse " style="border-radius:0;">

                @Html.Partial("_Nav")

            </nav>
        </div>

    </header>

    <main class="Main-Config">
        <section class="container">
            @RenderBody()
        </section>
    </main>

    <footer></footer>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/Scripts/Plugins/Boostrap3/bootstrap.min.js"></script>
    <script src="~/Scripts/Plugins/DataTables-1.10.18/js/jquery.dataTables.js"></script>
    <script src="~/Scripts/Plugins/DataTables-1.10.18/js/dataTables.bootstrap.min.js"></script>
    <script src="~/Scripts/Plugins/jQuery.slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/Scripts/Plugins/jQuery.Select2/select2.js"></script>
    <script src="~/Scripts/Plugins/jQuery.Select2/i18n/fa.js"></script>
    <script src="~/Scripts/Plugins/jQuery.toastr/toastr.min.js"></script>
    <script src="~/Scripts/Plugins/jQuery.slimscroll/jquery.slimscroll.min.js"></script>

    <script src="~/Scripts/MyScripts/DataTabels_Config.js"></script>
    <script src="~/Scripts/MyScripts/Toastr_Config.js"></script>
    <script src="~/Scripts/MyScripts/Select2_Config.js"></script>
    @Html.Partial("_Toster")

    @RenderSection("Scripts", false)

    @RenderSection("Modal", false)

    <script src="~/Scripts/modernizr-2.8.3.js"></script>

</body>
</html>

Wtiau.Health.Web/Views/Shared/_Modal.cshtml
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" style="z-index:1050">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="" id="myModalBody">

            </div>

        </div>
    </div>
</div>

Wtiau.Health.Web/Views/Shared/_Nav.cshtml
@using Wtiau.Health.Web.Models.Repository
@using Wtiau.Health.Web.Models.ViewModels;
@using Wtiau.Health.Web.Models.Domian;

@{
    if (User.Identity.IsAuthenticated)
    {
        if (User.IsInRole("Admin") || User.IsInRole("SuperAdmin"))
        {
            Rep_User info = new Rep_User();
            Model_AccountInfo infoModel = new Model_AccountInfo();
            infoModel = info.GetInfoForNavbar(User.Identity.Name);

            if (infoModel == null)
            {
                Response.Redirect("~/Account/Logout");
            }
            else
            {
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->
                        <li class="dropdown messages-menu menu-item ">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-envelope nav-top-userInfo-icon"></i>
                                <span class="label label-success">0</span>
                            </a>
                        </li>
                        <!-- Notifications: style can be found in dropdown.less -->
                        <li class="dropdown notifications-menu menu-item">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-bell nav-top-userInfo-icon" style="padding-right: 7px;"></i>
                                <span class="label label-warning">0</span>
                            </a>
                        </li>
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu menu-item ">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="glyphicon glyphicon-user  nav-top-userInfo-icon"></i>
                                <span class="hidden-xs nav-username">@infoModel.Name</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="~/Content/Images/abstract-user-flat-3.png" style="width:100px;height:100px;" class=" img-circle" alt="User Image">
                                    <p>
                                        @infoModel.Name
                                        <br />
                                        <small>@infoModel.Role</small>
                                    </p>
                                </li>
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="@Url.Action("index","Dashboard")" class="btn btn-default btn-flat" style="width:65px;">داشبورد</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="@Url.Action("Logout","Account")" class="btn btn-default btn-flat" style="width:65px;">خروج</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            }
        }
        else
        {
            Rep_Student info = new Rep_Student();
            Model_AccountInfo infoModel = new Model_AccountInfo();
            infoModel = info.GetInfoForNavbar(User.Identity.Name);
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">

                    @*<!-- Messages: style can be found in dropdown.less-->
                        <li class="dropdown messages-menu menu-item ">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-envelope nav-top-userInfo-icon"></i>
                                <span class="label label-success">0</span>
                            </a>

                        </li>
                        <!-- Notifications: style can be found in dropdown.less -->
                        <li class="dropdown notifications-menu menu-item">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-bell nav-top-userInfo-icon" style="padding-right: 7px;"></i>
                                <span class="label label-warning">0</span>
                            </a>

                        </li>*@
                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu menu-item ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                            <i class="glyphicon glyphicon-user  nav-top-userInfo-icon"></i>

                            <span class="hidden-xs nav-username">@infoModel.Name</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">


                                <img src="~/Content/Images/abstract-user-flat-3.png" style="width:100px;height:100px;" class=" img-circle" alt="User Image">

                                <p>
                                    @infoModel.Name
                                    <br />
                                    <small>@infoModel.Role</small>
                                </p>
                            </li>

                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="@Url.Action("index","Portal")" class="btn btn-default btn-flat" style="width:65px;">داشبورد</a>
                                </div>
                                <div class="pull-right">
                                    <a href="@Url.Action("PortalLogout","Account")" class="btn btn-default btn-flat" style="width:65px;">خروج</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        }
    }
    else
    {
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="btn navbar-btn nav-item-out-login ">
                    <a href="@Url.Action("PortalLogin","Account")" class="nav-item-out-login-a" style="padding:6px 0px 0px 0px;">
                        <i class="glyphicon glyphicon-education nav-item-out-login-a-i-login "></i>
                        <span class="hidden-xs " style="font-size:13px;">پرتال دانشجویان</span>
                    </a>

                </li>
            </ul>
        </div>

    }
}